<%-- 
    Document   : FreteIU
    Created on : Jan 9, 2013, 4:08:59 PM
    Author     : aalonso
--%>
<%--<%="METHOD=CallbackResponse&OFFERINSURANCEOPTION=false&L_SHIPPINGOPTIONLABEL0=e-Sedex&L_SHIPPINGOPTIONAMOUNT0=25.00&L_TAXAMT0=2.20&L_INSURANCEAMOUNT0=1.51&L_SHIPPINGOPTIONISDEFAULT0=false&L_SHIPPINGOPTIONLABEL1=Sedex&L_SHIPPINGOPTIONAMOUNT1=12.00&L_TAXAMT1=2.00&L_INSURANCEAMOUNT1=1.35&L_SHIPPINGOPTIONISDEFAULT1=true"%>--%>
<%="METHOD=CallbackResponse&OFFERINSURANCEOPTION=false&L_SHIPPINGOPTIONLABEL0=Entrega Expressa (4 dias)&L_SHIPPINGOPTIONAMOUNT0=5.64&L_SHIPPINGOPTIONISDEFAULT0=false&L_SHIPPINGOPTIONLABEL1=Entrega Turbo (12 horas)&L_SHIPPINGOPTIONAMOUNT1=10.00&L_SHIPPINGOPTIONISDEFAULT1=true&L_SHIPPINGOPTIONLABEL2=Entrega Economica (6 dias)&L_SHIPPINGOPTIONAMOUNT2=0.00&L_SHIPPINGOPTIONISDEFAULT2=false"%>